---
version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.11
    ports:
      - "5672:5672" #amqp
      - "15672:15672" #http
      - "15692:15692" #prometheus
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  amqp-sse-adapter:
    image: "dgoldsb/amqp-sse-adapter:latest"
    ports:
      - "8000:8000"
    environment:
      RUST_LOG: debug
      HOST: rabbitmq
      PORT: 5672
      USERNAME: guest
      PASSWORD: guest
      EXCHANGE: test_exchange
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: "."
      dockerfile: Dockerfile
